# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.1
    - name: Build
      run: make build
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        name: release
        body: "A new release"
        generate_release_notes: true
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: bin/*
        draft: false

